### ISSUE TITLE
Dérive fonctionnelle et modèle de données

### ISSUE THREAD

**Issue by nicolas-eoxia** [Eoxia/easycrm#173]
Adresse - llx_easycrm_address et address_card !!!! Warning duplication llx_socpeople et de contact/adresses card

**Comment by lmag** [comment]
1. Lister toutes les adresses crée dans la table adresse (EasyCRM)
2. Transférer cela dans la table contact/adresse
3. Créer le rôle "Projet-Adresse"


![image](https://github.com/Eoxia/easycrm/assets/3288514/21880e0a-c603-48c7-a193-a74b7a79bede)

**Comment by evarisk-micka** [comment]
Rajouter entité dans geolocation.sql
