### ISSUE TITLE
IHM - Score de relance problabilité opportunité

### ISSUE THREAD

**Issue by lmag** [Eoxia/easycrm#245]
Amélioration visuelle avec des couleurs

- [ ] Score 1 :
- [ ] Score 2 : 
- [ ] Score 3 : 
- [ ] Score 4 : 

![Image](https://github.com/Eoxia/easycrm/assets/3288514/1d51a46a-e1fc-439b-9229-31bd2559705e)

**Comment by evarisk-micka** [comment]
Score Relance donne la modification de la probabilité
Par exemple on part à 100% puis X% en moins par relances
