### ISSUE TITLE
Amélioration du dictionnaire evenement

### ISSUE THREAD

**Issue by lmag** [Eoxia/easycrm#250]
- [x] Création d'une issue sur Dolibarr https://github.com/Dolibarr/dolibarr/issues/30178
- [x] Rendre homogène les catégories sur EasyCRM

![Image](https://github.com/Eoxia/easycrm/assets/3288514/2caa2a06-2c0f-447c-8bc0-4012ace182d3)

**Comment by evarisk-micka** [comment]
/*$this->overwrite_translation = array(
			'en_US:ParentCompany'=>'Parent company or reseller',
			'fr_FR:ParentCompany'=>'Maison mère ou revendeur'
		)*/
