### ISSUE TITLE
relance rapide sur le listing des projets

### ISSUE THREAD

**Issue by lmag** [Eoxia/easycrm#7]
19d98a30d83bba65c785373e488411be4081708d

Création tache pour le temps consommé - SC - projet

62f8634481d9ba13f2292dea0a45f3edee316a6f

**Comment by lmag** [comment]
![Image](https://user-images.githubusercontent.com/3288514/221524009-18e4497c-eee7-4520-b38a-24cdce8776e7.png)

**Comment by lmag** [comment]
Relance direct avec le temps noté dans le projet dans la tache relance du projet

**Comment by lmag** [comment]
Le tri doit se faire par le statuts opportunités ouvertes (Natif Dolibarr) pas de TAG
Les couleurs devrait être crée par le statut opportunité

**Comment by lmag** [comment]
@eoxia-izza

**Comment by eoxia-izza** [comment]
Prospection : #FFEAC2
Qualification : #FFCD70
Proposition : #E37463
Négociation : #AB0420
Gagné : #ABAE6F
Perdu : #938A8C
